package commands

const (
	username        = "jrramos"
	main_branch     = "master"
	home_directory  = "/home/johnryanramos"
	notes_directory = home_directory + "/Documents/Notes/Day Log/Autogenerated/"
)
