package commands

import (
	"qk/internal"
	"strings"
	"testing"
)

func TestGitLog(t *testing.T) {
	commandString := internal.Qk(
		[]string{"git", "log", "--all"},
		commands,
		new(bool),
	)

	assertEqual(
		t,
		"git log --all --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)'",
		commandString,
	)
}

func TestGitNotes(t *testing.T) {
	commandString := internal.Qk(
		[]string{"note"},
		commands,
		new(bool),
	)

	assertEqual(
		t,
		strings.Join([]string{
			`cd "/home/johnryanramos/Documents/Notes/Day Log/Autogenerated/"`,
			`vim "$(date -d today +'%Y-%m-%d').md"`,
			`git add .`,
			`git commit -m "$(date -d today +'%Y-%m-%d')"`,
			`git push`,
			`exit 0`,
		}, "\n"),
		commandString,
	)
}

func TestGitNotesPreviousNote(t *testing.T) {
	commandString := internal.Qk(
		[]string{"note", "-1"},
		commands,
		new(bool),
	)

	assertEqual(
		t,
		strings.Join([]string{
			`cd "/home/johnryanramos/Documents/Notes/Day Log/Autogenerated/"`,
			`if [ ! -f "$(date -d today +'%Y-%m-%d').md" ]; then`,
			`	touch "/home/johnryanramos/Documents/Notes/Day Log/Autogenerated/$(date -d today +'%Y-%m-%d').md"`,
			`fi`,
			`last=$(ls | sort -V | tail -n 2 | head -1)`,
			`echo $last`,
			`vim -M $last`,
			`exit 0`,
		}, "\n"),
		commandString,
	)
}
