package user

import (
	"qk/internal/types/constructors"
	"qk/internal/types/definitions"
	"qk/internal/utils"
	"regexp"
	"strconv"
	"strings"
)

func GetUserCommands() []definitions.CustomCommand {
	return []definitions.CustomCommand{
		// Notes
		*constructors.NewCustomCommand(
			[]string{"note"},
			func(command []string, matches map[string]string) string {
				if strings.Contains(matches["note"], "-") {
					r := regexp.MustCompile(`-(?P<go_back>\d+)`)
					match := r.FindStringSubmatch(matches["note"])
					goBackInt, _ := strconv.Atoi(match[1])
					goBack := strconv.Itoa(goBackInt + 1)
					return utils.BuildMultilineCommandString([]string{
						"cd \"/home/johnryanramos/Documents/Notes/Day Log/Autogenerated/\"",
						"if [ ! -f \"$(date -d today +'%Y-%m-%d').md\" ]; then",
						"	touch \"/home/johnryanramos/Documents/Notes/Day Log/Autogenerated/$(date -d today +'%Y-%m-%d').md\"",
						"fi",
						"last=$(ls | sort -V | tail -n " + goBack + " | head -1)",
						"echo $last",
						"vim -M $last",
						"exit 0",
					})
				}
				return utils.BuildMultilineCommandString([]string{
					"cd \"/home/johnryanramos/Documents/Notes/Day Log/Autogenerated/\"",
					"vim \"$(date -d today +'%Y-%m-%d').md\"",
					"git add .",
					"git commit -m \"$(date -d today +'%Y-%m-%d')\"",
					"git push",
					"exit 0",
				})
			},
		),
		// VSCode
		*constructors.NewCustomCommand(
			[]string{"code"},
			func(command []string, matches map[string]string) string {
				return utils.AutoBuildCommandString(command, matches) + " . && exit 0"
			},
		),
	}
}
