package user

import (
	"qk/internal"
	"qk/internal/utils"
	"strings"
	"testing"
)

func TestGitNotes(t *testing.T) {
	commandString := internal.Qk(
		[]string{"note"},
		GetUserCommands(),
		new(bool),
	)

	utils.AssertEqual(
		t,
		strings.Join([]string{
			`cd "/home/johnryanramos/Documents/Notes/Day Log/Autogenerated/"`,
			`vim "$(date -d today +'%Y-%m-%d').md"`,
			`git add .`,
			`git commit -m "$(date -d today +'%Y-%m-%d')"`,
			`git push`,
			`exit 0`,
		}, "\n"),
		commandString,
	)
}

func TestGitNotesPreviousNote(t *testing.T) {
	commandString := internal.Qk(
		[]string{"note", "-1"},
		GetUserCommands(),
		new(bool),
	)

	utils.AssertEqual(
		t,
		strings.Join([]string{
			`cd "/home/johnryanramos/Documents/Notes/Day Log/Autogenerated/"`,
			`if [ ! -f "$(date -d today +'%Y-%m-%d').md" ]; then`,
			`	touch "/home/johnryanramos/Documents/Notes/Day Log/Autogenerated/$(date -d today +'%Y-%m-%d').md"`,
			`fi`,
			`last=$(ls | sort -V | tail -n 2 | head -1)`,
			`echo $last`,
			`vim -M $last`,
			`exit 0`,
		}, "\n"),
		commandString,
	)
}
